"""add_face_columns_to_employees

Revision ID: fa47000ab601
Revises: update_employee_face
Create Date: 2026-01-01 15:24:53.334248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa47000ab601'
down_revision = 'update_employee_face'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###